language: node_js
node_js: "8"
cache:
  yarn: true
branches:
  except:
    - /^v\d/

install:
  - yarn global add bower
  - yarn install
  - bower install

jobs:
  include:
    - stage: lint & integration test
      script:
        - yarn run lint
        - yarn run test:integration

    - stage: lighthouse test
      if: type IN pull_request
      script:
        - yarn global add firebase-tools
        - yarn add https://github.com/ebidel/lighthouse-ci
        - yarn run build
        - firebase deploy --token $FIREBASE_TOKEN --project abdonrd-develop
        - node node_modules/lighthouse-ci/runlighthouse.js https://abdonrd-develop.firebaseapp.com

    - stage: deploy to staging
      if: branch = develop
      env: NODE_ENV=staging
      script: yarn run build
      deploy:
        provider: firebase
        token: $FIREBASE_TOKEN
        skip_cleanup: true
        project: abdonrd-develop

    - stage: deploy to production
      if: branch = master
      env: NODE_ENV=production
      script: yarn run build
      deploy:
        provider: firebase
        token: $FIREBASE_TOKEN
        skip_cleanup: true
        project: project-8848054472830093819
