language: node_js
dist: trusty
sudo: required
addons:
  firefox: "latest"
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - "node"
  - "6"
cache:
  yarn: true
branches:
  except:
    - /^v\d/
install:
  - yarn global add bower
  - yarn install
  - bower install
script:
  - yarn run lint
  - xvfb-run yarn run test
  - xvfb-run yarn run test:integration
before_deploy:
  - if [ $TRAVIS_BRANCH = "develop" ]; then
      yarn run build;
    elif [ $TRAVIS_BRANCH = "master" ]; then
      yarn run build:production;
    fi
deploy:
  - provider: firebase
    token: $FIREBASE_TOKEN
    skip_cleanup: true
    project: abdonrd-develop
    on:
      branch: develop
  - provider: firebase
    token: $FIREBASE_TOKEN
    skip_cleanup: true
    project: project-8848054472830093819
    on:
      branch: master
