language: node_js
sudo: required
dist: trusty
node_js:
  - '6'
cache:
  directories:
    - node_modules
branches:
  except:
    - /^v\d/
install:
  - npm install -g bower
  - bower install
before_script:
  - npm run lint
script:
  - npm run build
deploy:
  - provider: firebase
    edge: true
    skip_cleanup: true
    project: abdonrd-develop
    token: "${FIREBASE_TOKEN}"
    on:
      branch: develop
  - provider: firebase
    edge: true
    skip_cleanup: true
    project: abdonrd
    token: "${FIREBASE_TOKEN}"
    on:
      branch: master
