language: node_js
sudo: required
dist: trusty
node_js:
  - '6'
cache:
  directories:
    - node_modules
branches:
  except:
    - /^v\d/
install:
  - npm install -g bower
  - bower install
before_script:
  - npm run lint
script:
  - npm run build
before_deploy:
  - openssl aes-256-cbc -K $encrypted_42359f73c124_key -iv $encrypted_42359f73c124_iv
    -in service-account.json.enc -out service-account.json -d
  - LAST_TAG=`git describe --abbrev=0` || LAST_TAG="develop"; echo $LAST_TAG
  - DEPLOY_VERSION=${LAST_TAG//.}
deploy:
  - provider: gae
    skip_cleanup: true
    project: abdonrd-com
    config: build/bundled/app.yaml
    version: develop
    no_promote: true
    on:
      branch: develop
  - provider: gae
    skip_cleanup: true
    project: abdonrd-com
    config: build/bundled/app.yaml
    version: $DEPLOY_VERSION
    on:
      branch: master
