runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /bower_components
  static_dir: bower_components

- url: /data
  static_dir: data

- url: /images
  static_dir: images

- url: /scripts
  static_dir: scripts

- url: /src
  static_dir: src

- url: /service-worker.js
  static_files: service-worker.js
  upload: service-worker.js

- url: /manifest.json
  static_files: manifest.json
  upload: manifest.json

- url: /LICENSE.txt
  static_files: LICENSE.txt
  upload: LICENSE.txt

- url: /.*
  static_files: index.html
  upload: index.html

skip_files:
- ^(.*/)?app\.yaml
